language: node_js

node_js:
  - stable

cache:
  directories:
    - 'node-modules'

services:
 - postgresql

before_script:
  - psql -c 'create database questionerdbtest;' -U postgres

install:
  - npm install

script:
  - npm test

after_script:
  - npm coverage
