language: node_js

node_js:
  - stable

cache:
  directories:
    - 'node-modules'

services:
 - postgresql

before_script:
  - psql -c 'create database questionerdbtest;' -U postgres

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  app: enigmatic-refuge-95413
  on:
    repo: dbytecoderc/Questioner
    branch: develop
  api_key:
    secure: "336755fd-e371-499e-8205-5491eb199f03"