language: node_js

node_js:
  - stable

cache:
  directories:
    - 'node-modules'

services:
 - postgresql

before_script:
  - psql -c 'create database questionerdbtest;' -U postgres

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  app: enigmatic-refuge-95413
  on:
    repo: dbytecoderc/Questioner
    branch: develop
  api_key:
    secure: "e6dac049-8736-4dbe-b0e8-5e8e0d06edd5"